Squid configurations for reverse proxy
filetrust/k8-reverse-proxy pull request #10
Opened 2020-09-03 11:26 UTC by NourEddineX

Squid packages used: https://github.com/filetrust/mvp-icap-squid-cache-proxy/tree/master/squid-deb-packages built with https://github.com/filetrust/mvp-icap-squid-cache-proxy/blob/master/squid-deb-packages/build.sh

**basic-squid-config/** : Squid configuration for reverse proxy mode with SSL Support
**basic-squid-config/squid.easy.conf** : Easy to use configuration for testing purposes, can be used with HTTP and plain IP address

2020-09-03 15:08 UTC, mahnouman requested changes
Please make sure the directory structure is in compliance with the project guidelines:
https://github.com/filetrust/Open-Source
Example repo is this one:
https://github.com/filetrust/k8-traffic-generator

2020-09-05 12:56 UTC, DinisCruz requested changes
Why are there binary files in the commit?

2020-09-06 09:10 UTC, MariuszFerdyn commented
The binnary was connected that docker build include Squid that it is included.

2020-09-06 17:08 UTC, DinisCruz approved these changes

2020-09-06 17:08 UTC, merged