Squid Reverse Proxy
filetrust/k8-reverse-proxy pull request #11
Opened 2020-09-04 10:36 UTC by hunnain

Squid Reverse Proxy

2020-09-04 11:32 UTC, mahnouman requested changes
Please make sure the directory structure is in compliance with the project guidelines:
https://github.com/filetrust/Open-Source
Example repo is this one:
https://github.com/filetrust/k8-traffic-generator

2020-09-04 18:23 UTC, mahnouman approved these changes

2020-09-04 21:23 UTC, mahnouman approved these changes

2020-09-05 12:54 UTC, DinisCruz approved these changes

2020-09-05 12:54 UTC, merged