Reference implementation for Squid Proxy on container
filetrust/k8-reverse-proxy pull request #13
Opened 2020-09-04 22:30 UTC by MariuszFerdyn

2020-09-04 22:31 UTC, MariuszFerdyn commented
Reference implementation for Squid Proxy on container

2020-09-05 12:52 UTC, DinisCruz requested changes
Can you fix the binary file comment?

2020-09-05 12:52 UTC, DinisCruz commented on MariuszFerdyn/v0-notes/README.md
> +
Hi, all of the commands above need to be executed inside a docker container

2020-09-05 12:52 UTC, DinisCruz commented on MariuszFerdyn/v1-ExternalConfig/README.md
> +
This needs to be converted to a kubernetes environment

2020-09-05 12:52 UTC, DinisCruz commented on MariuszFerdyn/v2-EmbededConfig/Dockerfile
> +FROM ubuntu:18.04
Why is the .deb file for squid proxy included?

2020-09-05 12:52 UTC, DinisCruz commented on MariuszFerdyn/v2-EmbededConfig/README.md
> +
Ok, looks like you already added k8 support :)

2020-09-06 09:15 UTC, MariuszFerdyn commented on MariuszFerdyn/v0-notes/README.md
> +
This is notes only - used for debug.

2020-09-06 09:35 UTC, MariuszFerdyn commented on MariuszFerdyn/v1-ExternalConfig/README.md
> +
But this is first version uses external configuration files - easy to debug.

Versions explanations:
v0-notes - only notes that can be used during deploying, debugging.
v1-ExternalConfig - config files are stored on external shared disk - it can be used for easy changing configuration etc.
v2-EmbededConfig - all configuration included in container.
v3-EnvConfig - I will work on it that all necessary config can be passed by Environment Variables.

2020-09-06 09:36 UTC, MariuszFerdyn commented on MariuszFerdyn/v2-EmbededConfig/Dockerfile
> +FROM ubuntu:18.04
Just Docker File uses it and put it to the image and install it.

2020-09-06 17:06 UTC, DinisCruz approved these changes

2020-09-06 17:06 UTC, merged